### ISSUE TITLE
Bug: clean_url fails on apostrophe in urls

### ISSUE THREAD

**Issue by mikewolfd** [adbar/courlan#106]
The clean_url function fails when a URL contains an apostrophe. I tried to quote/encode the URL, but it wouldn't parse & clean it correctly. 

The clean_url function should accept escaped/encoded URLs or better handle characters such as an apostrophe.

**Comment by adbar** [comment]
Thanks for your feedback, there seems to be a problem indeed, the cleaning component stops at an apostrophe and returns what was before.
